/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vistas;

import com.datos.Ingresos;
import static com.datos.Ingresos.EliminarIngreso;
import static com.datos.Ingresos.ListaIngresos;
import com.dominio.Ingreso;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class ingresos extends javax.swing.JPanel {

    /**
     * Creates new form Ingresos
     */
    public ingresos() {
        initComponents();
        cargarDatosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Ingreso = new javax.swing.JTable();
        Modificar_ingreso_btn = new javax.swing.JButton();
        Eliminar_ingreso_btn = new javax.swing.JButton();
        Agregar_ingreso_btn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        Tabla_Ingreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Ingreso);

        Modificar_ingreso_btn.setText("Modificar Ingreso");
        Modificar_ingreso_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Modificar_ingreso_btnActionPerformed(evt);
            }
        });

        Eliminar_ingreso_btn.setText("Eliminar Ingreso");
        Eliminar_ingreso_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Eliminar_ingreso_btnActionPerformed(evt);
            }
        });

        Agregar_ingreso_btn.setText("Agregar Ingreso");
        Agregar_ingreso_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_ingreso_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Modificar_ingreso_btn)
                        .addGap(31, 31, 31)
                        .addComponent(Eliminar_ingreso_btn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Agregar_ingreso_btn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modificar_ingreso_btn)
                    .addComponent(Eliminar_ingreso_btn)
                    .addComponent(Agregar_ingreso_btn))
                .addContainerGap(47, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Modificar_ingreso_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Modificar_ingreso_btnActionPerformed
         int selectedRow = Tabla_Ingreso.getSelectedRow();
        if(selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idIngreso = (int) Tabla_Ingreso.getValueAt(selectedRow, 1);
        String tipo_Ingreso = (String) Tabla_Ingreso.getValueAt(selectedRow, 1);
        Ingreso ingresoSeleccionado = new Ingreso();
        ingresoSeleccionado.setId_ingreso(idIngreso);
        if(!Ingresos.buscarIngreso_ID(ingresoSeleccionado)){
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el ingreso en la base de datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Modificar Ingreso", true);
            Modificar_Ingreso modificarIngresoPanel = new Modificar_Ingreso(ingresoSeleccionado);
            modificarIngresoPanel.cargarDatosEnCampo();
            modificarIngresoPanel.setDialog(dialog);
            dialog.add(modificarIngresoPanel);
            dialog.setSize(300, 443);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
            cargarDatosEnTabla();
            
    }//GEN-LAST:event_Modificar_ingreso_btnActionPerformed

    private void Eliminar_ingreso_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Eliminar_ingreso_btnActionPerformed
        int selectedRow = Tabla_Ingreso.getSelectedRow();
        if (selectedRow == -1){
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro valido", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "¿Esta seguro que desea eliminar el ingreso?", "Confirmar eliminacion", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            int idIngreso = (int) Tabla_Ingreso.getValueAt(selectedRow, 0);
            Ingreso ingresoSeleccionado = new Ingreso();
            ingresoSeleccionado.setId_ingreso(idIngreso);
            boolean eliminar = EliminarIngreso(ingresoSeleccionado);
            if(eliminar){
                JOptionPane.showMessageDialog(this, "Ingreso eliminado exitosamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosEnTabla();
            }else{
                JOptionPane.showMessageDialog(this, "Error al eliminar el ingreso", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Eliminar_ingreso_btnActionPerformed

    private void Agregar_ingreso_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_ingreso_btnActionPerformed
        JDialog dialog = new JDialog((JFrame) SwingUtilities.getWindowAncestor(this), "Agregar Ingreso", true);
        Agregar_Ingresos agregarIngresoPanel = new Agregar_Ingresos();
        agregarIngresoPanel.setDialog(dialog);
        dialog.add(agregarIngresoPanel);
        dialog.setSize(300, 443);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        cargarDatosEnTabla();
    }//GEN-LAST:event_Agregar_ingreso_btnActionPerformed
     private void cargarDatosEnTabla(){
        List<Ingreso> listaIngresos = ListaIngresos();
        DefaultTableModel model = (DefaultTableModel) Tabla_Ingreso.getModel();
        model.setRowCount(0);
            for(Ingreso i: listaIngresos){
                model.addRow(new Object[]{
                    i.getId_ingreso(),
                    i.getTipo_pago(),
                    i.getDia_ingreso(),
                    i.getMes_ingreso(),
                    i.getA_ingreso(),
                    i.getDpto(),
                    i.getMonto(),
                    i.getDNI_encargado()
                });
            }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_ingreso_btn;
    private javax.swing.JButton Eliminar_ingreso_btn;
    private javax.swing.JButton Modificar_ingreso_btn;
    private javax.swing.JTable Tabla_Ingreso;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
